[project]
name = "week_1_project"
version = "0.1.0"
description = "Flask CRUD API for student records"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "Flask>=3.1.2",
  "python-dotenv>=1.1.1",
]
